spring.application.name=UM-SERVICE


server.port=9095
spring.mvc.view.suffix=.jsp

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/um
spring.datasource.username=root
spring.datasource.password=uma12345
spring.jpa.hibernate.ddl-auto=update

spring.redis.host=localhost
spring.redis.port=6379



